apiKey: "None"
apiKeyRequired: false
url: "http://localhost:11434/api/chat"
model: "vanilj/phi-4-unsloth"
#model: "hf.co/unsloth/phi-4-GGUF:Q6_K"
#model: "hf.co/unsloth/phi-4-GGUF:Q5_K_M"
modelParams:
  temperature: 0.2
  max_tokens: 4096
  top_p: 0.9
  top_k: 40
  min_p: 0.5
  frequency_penalty: 0
  presence_penalty: 0
  num_ctx: 8192
retryCount: 20
batchSize: 1
skipLineValidation: false
correctionPromptsEnabled: false
translateFlagged: true